version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - godot
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    revive:
      rules:
        - name: bare-return
        - name: bool-literal-in-expr
        - name: comment-spacings
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: error-naming
        - name: error-return
        - name: exported
          arguments:
            - "check-private-receivers"
            - "disable-stuttering-check"
        - name: indent-error-flow
        - name: modifies-value-receiver
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: struct-tag
        - name: use-any
        - name: useless-break
        - name: var-declaration
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: "ST1005:"
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lxc/terraform-provider-incus)
    goimports:
      local-prefixes:
        - github.com/lxc/terraform-provider-incus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
