version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - godot
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - testifylint
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: "ST1005:"
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lxc/terraform-provider-incus)
    goimports:
      local-prefixes:
        - github.com/lxc/terraform-provider-incus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
